# Uncomment the next line to define a global platform for your project
 
@flutter_application_path = '../flutter_module/'
def flutter_source_project_embased_function()
  load File.join(@flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(@flutter_application_path)
end

platform :ios, '9.0'

target 'HybridiOSApp' do
flutter_source_project_embased_function
  use_frameworks!

  # Pods for HybridiOSApp
end

